# -*- coding: utf-8 -*-
"""ML Day-1 Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9DsP97uvnfo74zl_rJilcu-bl_1Yzv4
"""

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/House_price_predictionCopy.csv')

from sklearn.linear_model import LinearRegression
#from sklearn import linear_model
#reg=linear_model.LinearRegression()
reg=LinearRegression()
x=df[['SQUARE_FT']]                                          
y=df['TARGET(PRICE_IN_LACS)']
reg.fit(x,y)

plt.scatter(df['SQUARE_FT'],df['TARGET(PRICE_IN_LACS)'])
plt.show()
print(reg.predict([[1275]]))

print("Coefficient",reg.coef_)
print("Intercept",reg.intercept_)

y=.21980607*1275-201.91195205784362
print(y)

from sklearn.model_selection import train_test_split
X=df[['BHK_NO.','SQUARE_FT']]
y=df['TARGET(PRICE_IN_LACS)']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
reg1=LinearRegression()
reg1.fit(X_train,y_train)
print(reg1.predict(X_test))

print(reg1.coef_)
print(reg1.intercept_)

print(reg1.predict([[1275,1]]))

yy=33.47962778*0+.21944339*1275-33.47962778-179.8509412690343
print(yy)