# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uZcOMDxSZr6dcIgdIlgsX9UdX85m9gt
"""

import pandas as pd
from sklearn.datasets import load_iris
dic=load_iris()
print(dic)

df=pd.DataFrame(dic['data'],columns=dic['feature_names'])

print(df)

df['target']=dic['target']
print(df)

X=df.drop('target',axis='columns')
y=df['target']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=9)
from sklearn.svm import SVC
model=SVC(kernel='poly')
model.fit(X_train,y_train)

print(model.predict([[5.5,3.6,2.1,1.0]]))

print(model.predict(X_test))

print(model.score(X_test,y_test))