# -*- coding: utf-8 -*-
"""Matplotlib Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eki54-H_UHOVY_bXLrLsB1wGNdKkPaAv

# **scatter**
"""

import matplotlib.pyplot as plt
import pandas as pd
#x=[10,20,30,40,50]
#y=[1,2,3,4,5]
#plt.scatter(x,y)
df=pd.read_csv('/content/IRIS.csv')

plt.scatter(df.sepal_length,df.sepal_width)
plt.show()

x=[10,20,30,40,50]
y=[1,2,3,4,5]
plt.scatter(x,y,color='red')
p=[1,1,1,1,1]
q=[1,2,3,4,5]
plt.scatter(p,q,color='green')
plt.show()

x=[10,20,30,40,50]
y=[1,2,3,4,5]
plt.scatter(x,y,color=['red','green','blue','pink','cyan'])
plt.show()

import random
x=[10,20,30,40,50]
y=[1,2,3,4,5]
plt.scatter(x,y,c=[random.randint(0,100) for i in range(5)],cmap='viridis')
plt.show()

x=[10,20,30,40,50]
y=[1,2,3,4,5]
plt.scatter(x,y,s=[10,20,40,80,160])
plt.show()

x=[10,20,30,40,50]
y=[1,2,3,4,5]
plt.scatter(x,y,s=[10,20,40,80,160],alpha=0.9)
plt.show()

"""# **Bars**"""

categories=['A','B','C','D']
y=[10,20,30,40]
plt.bar(categories,y)
plt.show()

categories=['A','B','C','D']
y=[10,20,30,40]
plt.barh(categories,y)
plt.show()

categories=['A','B','C','D']
y=[10,20,30,40]
plt.bar(categories,y,color=['cyan','magenta','red','pink'])
plt.show()

categories=['A','B','C','D']
y=[10,20,30,40]
plt.bar(categories,y,width=0.5)
plt.show()

categories=['A','B','C','D']
y=[10,20,30,40]
plt.barh(categories,y,height=.1)
plt.show()

"""# **piechart**"""

a=[10,20,30,40]
b=['I','II','III','IV']
c=['red','green','blue','cyan']
plt.pie(a,labels=b,colors=c,startangle=0,explode=[0.2,0,0,0],shadow=True)
plt.show()

a=[10,20,30,40]
b=['I','II','III','IV']
c=['red','green','blue','cyan']
plt.pie(a,labels=b,colors=c,startangle=0,explode=[0.2,0,0,0],shadow=True)
plt.legend()
plt.show()

a=[10,20,30,40]
b=['I','II','III','IV']
c=['red','green','blue','cyan']
plt.pie(a,labels=b,colors=c,startangle=0,explode=[0.2,0,0,0],shadow=True)
plt.legend(title='4 Categories:-')
plt.show()

a=[1,2,3,40]
b=['I','II','III','IV']
c=['red','green','blue','cyan']
plt.pie(a,labels=b,colors=c,startangle=0,autopct='%.1f%%')
plt.show()

a=[1,2,3,40]
b=['I','II','III','IV']
c=['red','green','blue','cyan']
plt.pie(a,labels=b,colors=c,startangle=0,autopct='%.1f%%',wedgeprops={'edgecolor':'magenta','linewidth':4})
plt.show()