# -*- coding: utf-8 -*-
"""Matplotlib Day-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ve6R2EFcfqEnJNorp28IZnZ3DCx4dk8j

# **MARKERS**

'o'	Circle	
'*'	Star	
'.'	Point	
','	Pixel	
'x'	X	
'X'	X (filled)	
'+'	Plus	
'P'	Plus (filled)	
's'	Square	
'D'	Diamond	
'd'	Diamond (thin)	
'p'	Pentagon	
'H'	Hexagon	
'h'	Hexagon	
'v'	Triangle Down	
'^'	Triangle Up	
'<'	Triangle Left	
'>'	Triangle Right	
'1'	Tri Down	
'2'	Tri Up	
'3'	Tri Left	
'4'	Tri Right	
'|'	Vline	
'_'	Hline
"""

import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[6,7,8,9,10]
plt.plot(x,y,marker='>')
plt.show()

"""# **marker|line|color**

# **line**

'-'	Solid line	
':'	Dotted line	
'--'	Dashed line	
'-.'	Dashed/dotted line

# **color**

'r'	Red	
'g'	Green	
'b'	Blue	
'c'	Cyan	
'm'	Magenta	
'y'	Yellow	
'k'	Black	
'w'	White
"""

x=[1,2,3,4,5]
y=[6,7,8,9,10]
plt.plot(x,y,'D--c')      
plt.show()

"""other keyword parameters:-

## 1. **markersize** **ms**
## 2. **markeredgecolor** **mec**
## 3. **markerfacecolor** **mfc**
"""

x=[1,2,3,4,5]
y=[6,7,8,9,10]
plt.plot(x,y,'P--r',ms=20,markeredgecolor='m',markerfacecolor='c')
plt.show()

"""Alternative of **line|color** of **marker|line|color**

Attributes:-

**1. linestyle or ls**

**2. color or c**

Other Attribute is:

**1. linewidth or lw**

"""

x=[1,2,3,4,5]
y=[6,7,8,9,10]
plt.plot(x,y,ls='dotted',c='c',linewidth=10)
plt.show()

"""# Plotting Multiples Lines with:-
**1. Single plot() Method**

**2. Multiple plot() method**
"""

x=[1,2,3,4,5]
y=[6,7,8,9,10]
p=[10,20,30]
q=[5,10,15]
a=(3,4)
b=(9,16)
plt.plot(x,y,p,q,a)       
plt.show()

x=[1,2,3,4,5]
y=[6,7,8,9,10]
p=[10,20,30]
q=[5,10,15]
a=(3,4)
b=(9,16)
plt.plot(x,y)
plt.plot(p,q)
plt.plot(a,b)
plt.show()

"""# Attibutes of xlabel(), ylabel(), title():-
**1. fontdict={'family':'serif','color':'red','size':2}** for all 3 methods

**2. loc='left' or 'right' or 'center'**    for title() only
"""

x=[5,2,3,4,1]
y=[10,7,8,9,6]
plt.plot(x,y)

plt.title('GRAPH',fontdict={'family':'serif','color':'red','size':20})
plt.xlabel('X axis',fontdict={'family':'fantasy','color':'green','size':10})
plt.ylabel('Y axis',fontdict={'family':'Tahoma','color':'magenta','size':10})
plt.show()

"""# Grid
Attributes:-

**1.axis='x' or 'y' or 'both' or None**

**2.color or c**

**3.linestyle or ls**

**4.linewidth or lw**
"""

#x=[1,2,3,4,5]
#y=[6,7,8,9,10]
x=[]
y=[]
plt.plot(x,y)
plt.grid(axis='x')
#plt.grid(c='r',ls='dashed',lw=1)
plt.show()

"""# subplot
**1.subplot(rows,cols,index)**

**2.suptitle()**
"""

plt.suptitle('Country')
plt.subplot(2,1,1)
plt.title('USA')
plt.subplot(2,1,2)
plt.title('India')
plt.show()

"""# Scatter"""