# -*- coding: utf-8 -*-
"""DBSCAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-phGheNCBw0rU22BLMbBuj7eVmQfqR3W
"""

import pandas as pd
df=pd.read_csv('IRIS.csv')
df

X=df[['sepal_length','sepal_width','petal_length','petal_width']]

from sklearn.cluster import DBSCAN
model=DBSCAN(eps=0.7,min_samples=2)

model1=model.fit(X)

labels=model1.labels_
print(labels)

import numpy as np
arr=np.zeros_like(labels,dtype=bool)
arr

arr[model1.core_sample_indices_]=True

arr

noc=len(set(labels))-(1 if -1 in labels else 0)

print(noc)

from sklearn.metrics import silhouette_score
print(silhouette_score(X,labels))