# -*- coding: utf-8 -*-
"""File Processing 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5e52biuFeOtu1xNa1GMTyxCzLYETLKE
"""

import cv2
from google.colab.patches import cv2_imshow
img=cv2.imread('3boys.jpg')                          #cv2.imread('3boys.jpg',1)       1,0,-1
print('Size of Image',img.shape)
print(img)
print('######################')                       
cv2_imshow(img)                                       #cv2.imshow('window name',img)
#cv2.waitKey(0)    
#cv2.waitKey(4000)
#cv2.destroyAllWindows()

"""# **Resizing Image**"""

img2=cv2.resize(img,(200,100))                       #cv2.resize(Resize what,Resize with)
cv2_imshow(img2)

"""# **Grayscale Image**"""

img3=cv2.imread('3boys.jpg',0)
cv2_imshow(img3)

"""# **Write the Image or Save the image**"""

cv2.imwrite('/content/3boys_grayscale.jpg',img3)

"""# **Flipping the Image**"""

img4=cv2.flip(img,1)                                # 1,0,-1
img5=cv2.flip(img,0)
img6=cv2.flip(img,-1)
cv2_imshow(img4)
cv2_imshow(img5) 
cv2_imshow(img6)