# -*- coding: utf-8 -*-
"""Ridge and Lasso Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZGwEGQtfQ3t4ZUk9ni_vkefvp8xZwqK

# Ridge **Regression**
"""

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
model=Ridge()

parameters={'alpha':[1,2,5,10,20,30,40,50,60,70,80,90,100]}
newmodel=GridSearchCV(model,parameters,scoring='neg_mean_squared_error',cv=5)

import pandas as pd
df=pd.read_csv('/content/House_price_predictionCopy.csv')
X=df[['SQUARE_FT']]
y=df['TARGET(PRICE_IN_LACS)']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=9)

newmodel.fit(X_train,y_train)

print(newmodel.best_params_)

#print(newmodel.best_score_)

y_pred=newmodel.predict(X_test)
print(y_pred)

from sklearn.metrics import r2_score
r2score=r2_score(y_pred,y_test)
print(r2score)

import seaborn as sns
sns.displot(y_pred-y_test,kind='kde')

"""# **Lasso** **Regression**    same as Ridge 
model=Lasso()


GridSearchCV(model,.....)
"""