# -*- coding: utf-8 -*-
"""LDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTyAoP-CmSFR_HVAfEJywIhChwtDl1Lo
"""

from sklearn.datasets import load_wine
dic=load_wine()
print(dic.keys())

print(dic['data'])
print(dic['target'])
print(dic['target_names'])

print(dic['data'].shape)

print(dic['feature_names'])

X=dic['data']
y=dic['target']



print(dic['DESCR'])

print(X.shape)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda=LinearDiscriminantAnalysis()
X_lda=lda.fit_transform(X,y)
print(X_lda.shape)

print(lda.explained_variance_ratio_)

import matplotlib.pyplot as plt
plt.scatter(X_lda[:,0],X_lda[:,1],c=y,cmap='rainbow',edgecolors='green')
plt.xlabel('LDA 1')
plt.ylabel('LDA 2')
plt.show()